# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=1024),
        ),
    ]
